openapi: 3.0.0
info:
  title: "API Flask"
  description: "Departments and Employees"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /employees:
    get:
      operationId: "services.read_all_employees"
      tags:
        - "Employees"
      summary: "Read the list of employees"
      responses:
        "200":
          description: "Successfully read employees list"

  /departments:
    get:
      operationId: "services.read_all_departments"
      tags:
        - "Departments"
      summary: "Read the list of departments"
      responses:
        "200":
          description: "Successfully read departments list"

  /dependents:
    get:
      operationId: "services.read_all_dependents"
      tags:
        - "Dependents"
      summary: "Read the list of employees by department"
      responses:
        "200":
          description: "Successfully read employees by department list"

