openapi: 3.0.0
info:
  title: "API Flask"
  description: "Departments and Employees"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Departments:
      type: "object"
      required:
        - name
      properties:
        name:
          type: "string"
  parameters:
    name:
      name: "name"
      description: "Name of department to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /employees:
    get:
      operationId: "services.read_all_employees"
      tags:
        - "Employees"
      summary: "Read the list of employees"
      responses:
        "200":
          description: "Successfully read employees list"

  /departments:
    get:
      operationId: "services.read_all_departments"
      tags:
        - "Departments"
      summary: "Read the list of departments"
      responses:
        "200":
          description: "Successfully read departments list"

  /departments/{name}:
    get:
      operationId: "services.get_employees_by_department_result"
      tags:
        - "Departments"
      summary: "Return departments with list employees"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully read departments list"

  /dependents:
    get:
      operationId: "services.read_all_dependents"
      tags:
        - "Dependents"
      summary: "Read the list of employees by department"
      responses:
        "200":
          description: "Successfully read employees by department list"
